### ISSUE TITLE
We don't need to use `verifiedQueryClient` for `TxBuilder`

### ISSUE THREAD

**Issue by youngjoon-lee** [medibloc/panacea-oracle#45]
The [TxBuilder](https://github.com/medibloc/panacea-oracle/blob/18cf18d91af0d27f2e9bfb58025d9fb36bf0e486/panacea/tx.go#L14) requires [QueryClient](https://github.com/medibloc/panacea-oracle/blob/18cf18d91af0d27f2e9bfb58025d9fb36bf0e486/panacea/query_client.go#L35) only for [GetAccount](https://github.com/medibloc/panacea-oracle/blob/18cf18d91af0d27f2e9bfb58025d9fb36bf0e486/panacea/tx.go#L59), and we're using a verifiedQueryClient for [NewTxBuilder](https://github.com/medibloc/panacea-oracle/blob/7c2eb368e1db299e25298975f772cd1e9aa699b4/service/service.go#L81). But I don't see any risk yet even if we use a normal queryClient instead of verifiedQueryClient (which contains light client). If my thought is true, let's use a normal query client for TxBuilder since it's way faster than verifiedQueryClient.

The reason why we adopted the light client is that any malicious guy can trick the oracle with false information, such as fake deal info or fake oracle private key. But, the account info which is required by TxBuilder is not that crucial, I think. Oracle does some off-chain operations using oracle private key or deal info (which contains the consumer info), such as issuing certificates or encrypting data for consumers. Because there is no safety checker for these off-chain operations, we need the light client in order to decide whether we should start an off-chain operation based on the info fetched from the chain, or not.

However, the TxBuilder doesn't do any off-chain operation. That does only one operation, broadcasting txs, which is definitely performed on-chain. On-chain operations are validated by chain validators. If someone tricks the TxBuilder with fake account info, the txs executed by TxBuilder won't be accepted by chain validators. Of course, that malicious guy can run her own chain node, but she won't be able to beat voting powers of other validators.

Let's think whether my theory is correct.

**Comment by gyuguen** [comment]
Yes, I think your opinion is correct.
We can possible changed `verifiedQueryClient` to `grpcClient`.

**Comment by H4NLee** [comment]
Agree. we don't need to use verified query client for tx builder.
