### ISSUE TITLE
Speed up the verifiedQueryClient using goroutines

### ISSUE THREAD

**Issue by youngjoon-lee** [medibloc/panacea-oracle#46]
Currently, the verifiedQueryClient makes a ABCI query based on the latest block, and wait for the next block (= `latest + 1`) for light client verification.
But, there are some cases where we need to query multiple values from the chain. For example, we need to fetch a deal, a certificate, and an account for handling `GET /v0/.../secret-key`.

To speed up it, use goroutines.

There are two ways, in general. We should decide about it.
1. Spawning goroutines whenever you want.
2. Limiting the max number of goroutines for a verifiedQueryClient (similar as a thread pool).

It depends on the rate limiting of the chain node.

**Comment by gyuguen** [comment]
I think we have a way to achieve the same effect as goroutines.

1. We get lastBlockHeight before searching.
2. And we use this height for all out queryies.

Theoretically, we can run multiple queries in 0 to 6 seconds.

**Comment by youngjoon-lee** [comment]
Good idea. Let's migrate this discussion to #47 since it's related more with queryHeight rather than goroutines.
