### ISSUE TITLE
Implement HTTP Signature Authentication

### ISSUE THREAD

**Issue by youngjoon-lee** [medibloc/panacea-oracle#50]
- Implement the HTTP Signature Authentication using `<requestID, nonce>`
- Use this authentication for the data downloading API: https://github.com/medibloc/panacea-data-market-validator/issues/49.

### Parameter Spec
- requestID: A UUID is a 128 bit (16 byte) Universal Unique IDentifier as defined in RFC 4122.
- nonce: [a-zA-Z0-9/]{24}
  - Randomly create a byte array of length 24
  - encode to standard base64(length: 32)
  - ex) `fS/ueIknAzJd8PvrUsDBmweOT9q9H90r`

### How to check authentication
- It uses the cache module [go-cache](https://github.com/patrickmn/go-cache)
  - The cache stores authentication request information.
  - A valid cache time of 10 minutes
  - If the download is completed using this authentication, the request information stored in the cache is deleted.
  - Need to discuss when the generate requestID.
- The following headers must be received on the first call
```
# Authorization: Signature
    keyId="{panaceaAccAddr}",
    algorithm="es256k1-sha256",
    nonce="",
    signature=""
```
- Parse the authentication information in the header
- It validates the header like below.
```
# Authorization: Signature
    keyId="{panaceaAccAddr}",
    algorithm="es256k1-sha256",
    nonce="{nonceReceivedFromServer}",
    signature="{base64(sign(es256k1PrivKey, sha256(append(keyId, nonce))))}"
``` 
- If the required header information is not received, it responds as follows.
```
 # Status code: 401 Unauthorized
 # WWW-Authenticate: Signature
    keyId="{keyIdReceivedFromClient}",
    algorithm="es256k1-sha256",
    nonce="{randomNonce}",
```
- The `nonce` and `requestID` expire a  fter 5 minutes.(It is possible change)
- If request is successful, the header responds as follows.
```
 # Status code: 200 Ok
 # WWW-Authenticate: Signature
    keyId="{keyIdReceivedFromClient}",
    algorithm="es256k1-sha256",
    nonce="{newRandomNonce}",
```

**Comment by gyuguen** [comment]
I have defined the spec for this issue.
